FORMAT: 1A
HOST: http://localhost/api

# FORTYPES

It's a documentation for Fortypes API

## Fonts Collection [/fonts]

### List All Fonts [GET]

Get list of all published fonts

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "content": "THE",
                "author_name": "Mr. Ivan Smith",
                "status": "on_review",
                "image": {
                    "id": 232,
                    "image_original": "http://testserver/api/fonts/test_file_Buu1X6g.jpg",
                }
                "symbols": [
                    {
                        "value": "T",
                        "point_one_x": 0.2,
                        "point_one_y": 0.2,
                        "point_two_x": 2.2,
                        "point_two_y": 2.2,
                    }, 
                    {
                        "value": "H",
                        "point_one_x": 2.2,
                        "point_one_y": 0.2,
                        "point_two_x": 4.2,
                        "point_two_y": 2.2,
                    }, 
                    {
                        "value": "E",
                        "point_one_x": 4.2,
                        "point_one_y": 0.2,
                        "point_two_x": 6.2,
                        "point_two_y": 2.2,
                    }, 
                ]
            },
        ]

### Create a New Font [POST]

Request to create new font

+ Request (application/json)

        {
                "title": "title",
                "author_name": "Mr. Author", # optional
                "image_id": 242525,
                "content": "THE",
                
                "symbols": [
                    {
                        "value": "T",
                        "point_one_x": 0.2,
                        "point_one_y": 0.2,
                        "point_two_x": 2.2,
                        "point_two_y": 2.2,
                    }, 
                    {
                        "value": "H",
                        "point_one_x": 2.2,
                        "point_one_y": 0.2,
                        "point_two_x": 4.2,
                        "point_two_y": 2.2,
                    }, 
                    {
                        "value": "E",
                        "point_one_x": 4.2,
                        "point_one_y": 0.2,
                        "point_two_x": 6.2,
                        "point_two_y": 2.2,
                    }, 
                ]
            }

+ Response 201 (application/json)


## Image Files [/font_upload/{file_name.jpg}]

### Upload Font Image [POST]

Upload image and get image id before create a font

+ Request (multipart)

        {
            "image": "", # binary file data,

        }

+ Response 200 (application/json)

        {
            "id": 232,
            "image_original": "http://testserver/api/fonts/test_file_Buu1X6g.jpg",
        }