FORMAT: 1A
HOST: http://localhost/api

# FORTYPES

It's a documentation for Fortypes API

## Fonts Collection [/fonts]

### List All Fonts [GET]

Get list of all published fonts

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "content": "THE",
                "author_name": "Mr. Ivan Smith",
                "status": "on_review",
                "image": "http://testimagehost.com/test_image.jpg",
                "image_thumbnail": "http://testimagehost.com/test_sm_image.jpg", 
                "symbols": [
                    {
                        "value": "T",
                        "point_one_x": 0.2,
                        "point_one_y": 0.2,
                        "point_two_x": 2.2,
                        "point_two_y": 2.2,
                    }, 
                    {
                        "value": "H",
                        "point_one_x": 2.2,
                        "point_one_y": 0.2,
                        "point_two_x": 4.2,
                        "point_two_y": 2.2,
                    }, 
                    {
                        "value": "E",
                        "point_one_x": 4.2,
                        "point_one_y": 0.2,
                        "point_two_x": 6.2,
                        "point_two_y": 2.2,
                    }, 
                ]
            },
        ]

### Create a New Font [POST]

Request to create new font

+ Request (application/json)

        {
                "content": "THE",
                "symbols": [
                    {
                        "value": "T",
                        "point_one_x": 0.2,
                        "point_one_y": 0.2,
                        "point_two_x": 2.2,
                        "point_two_y": 2.2,
                    }, 
                    {
                        "value": "H",
                        "point_one_x": 2.2,
                        "point_one_y": 0.2,
                        "point_two_x": 4.2,
                        "point_two_y": 2.2,
                    }, 
                    {
                        "value": "E",
                        "point_one_x": 4.2,
                        "point_one_y": 0.2,
                        "point_two_x": 6.2,
                        "point_two_y": 2.2,
                    }, 
                ]
            }

+ Response 201 (application/json)