---
securityDefinitions:
  basic:
    type: basic
info:
  title: Docs for API
  version: ''
host: 127.0.0.1:8000
paths:
  "/fonts/{pk}/":
    delete:
      responses:
        '204':
          description: ''
      description: ''
      tags:
      - fonts
      parameters:
      - name: pk
        description: ''
        required: true
        type: string
        in: path
    get:
      responses:
        '200':
          description: ''
      description: ''
      tags:
      - fonts
      parameters:
      - name: pk
        description: ''
        required: true
        type: string
        in: path
    patch:
      responses:
        '200':
          description: ''
      description: ''
      tags:
      - fonts
      parameters:
      - name: pk
        description: ''
        required: true
        type: string
        in: path
      - name: title
        description: test text
        required: false
        type: string
        in: formData
      - name: author
        description: ''
        required: false
        type: string
        in: formData
      - name: status
        description: ''
        required: false
        type: string
        in: formData
    put:
      responses:
        '200':
          description: ''
      description: ''
      tags:
      - fonts
      parameters:
      - name: pk
        description: ''
        required: true
        type: string
        in: path
      - name: title
        description: test text
        required: true
        type: string
        in: formData
      - name: author
        description: ''
        required: true
        type: string
        in: formData
      - name: status
        description: ''
        required: true
        type: string
        in: formData
  "/fonts/{pk}/docs/":
    get:
      responses:
        '200':
          description: ''
      description: ''
      tags:
      - fonts
      parameters:
      - name: pk
        description: ''
        required: true
        type: string
        in: path
  "/fonts/":
    post:
      responses:
        '201':
          description: ''
      description: ''
      tags:
      - fonts
      parameters:
      - name: title
        description: test text
        required: true
        type: string
        in: formData
      - name: author
        description: ''
        required: true
        type: string
        in: formData
      - name: status
        description: ''
        required: true
        type: string
        in: formData
    get:
      responses:
        '200':
          description: ''
      description: ''
      tags:
      - fonts
      parameters:
      - name: page
        description: ''
        required: false
        type: string
        in: query
swagger: '2.0'
