# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:04
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_original', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='')),
            ],
        ),
    ]
