# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 12:41
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageobj',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
    ]
