# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collections_posts.CollectionImagesBlock'),
        ),
    ]
