# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fonts', '0005_auto_20161203_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFontRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('shared_facebook', models.BooleanField(default=False)),
                ('shared_vk', models.BooleanField(default=False)),
                ('shared_twitter', models.BooleanField(default=False)),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relation', to='fonts.Font')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font_relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
