# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fonts', '0005_auto_20161203_1053'),
        ('user_font_relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFontRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderated', models.BooleanField(default=False)),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_relation', to='fonts.Font')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_font_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
