# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20161203_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_invites', to='accounts.Account')),
                ('user_who_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
