# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='test text', max_length=200)),
                ('status', models.SlugField(choices=[('private', 'private'), ('on_review', 'on_review'), ('public', 'public')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='accounts.Account')),
            ],
        ),
    ]
