# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fonts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('point_one_x', models.FloatField()),
                ('point_one_y', models.FloatField()),
                ('point_two_x', models.FloatField()),
                ('point_two_y', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='font',
            name='title',
        ),
        migrations.AddField(
            model_name='font',
            name='content',
            field=models.CharField(help_text='content', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='font',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ImageObj'),
        ),
        migrations.AlterField(
            model_name='font',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='font',
            name='status',
            field=models.SlugField(choices=[('private', 'private'), ('on_review', 'on_review'), ('public', 'public')], default='on_review'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='font',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='fonts.Font'),
        ),
    ]
