# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('ul_point', models.PositiveSmallIntegerField()),
                ('ur_point', models.PositiveSmallIntegerField()),
                ('dl_point', models.PositiveSmallIntegerField()),
                ('dr_point', models.PositiveSmallIntegerField()),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='fonts.Font')),
            ],
        ),
    ]
