# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 09:26
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('point_one_x', models.FloatField()),
                ('point_one_y', models.FloatField()),
                ('point_two_x', models.FloatField()),
                ('point_two_y', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='font',
            name='title',
        ),
        migrations.AddField(
            model_name='font',
            name='content',
            field=models.CharField(default=None, help_text='content', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='font',
            name='image',
            field=models.ImageField(default=None, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='font',
            name='status',
            field=models.SlugField(choices=[('private', 'private'), ('on_review', 'on_review'), ('public', 'public')], default='on_review'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='font',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='fonts.Font'),
        ),
    ]
