# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0002_auto_20161026_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='font',
            old_name='author',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='font',
            name='author_name',
            field=models.CharField(blank=True, help_text='author_name', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='font',
            name='image',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ImageObj'),
            preserve_default=False,
        ),
    ]
