# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0003_auto_20160911_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='position',
            field=models.IntegerField(unique=True),
        ),
    ]
